### ISSUE TITLE
Initial Spring Boot Support

### ISSUE THREAD

**Issue by jimmyjames** [openfga/spring-boot-starter#3]
Epic to contain v0 support for FGA with Spring Security.

This work broadly entails:
- Enabling the configuration of an `OpenFgaClient` bean
- A simple FGA check to be used at least for pre-method invocation security (no contextual tuples or context, or list API support; those will come later)

Tasks:

- [x] #17
- [x] #18
- [x] #15 
- [x] https://github.com/openfga/fga-spring-boot/issues/11
- [x] https://github.com/openfga/fga-spring-boot/issues/4
- [x] https://github.com/openfga/fga-spring-boot/issues/5
- [x] https://github.com/openfga/fga-spring-boot/issues/7
- [x] https://github.com/openfga/fga-spring-boot/issues/8
- [x] https://github.com/openfga/fga-spring-boot/issues/1
- [x] https://github.com/openfga/fga-spring-boot/issues/9
- [x] https://github.com/openfga/fga-spring-boot/issues/10
- [x] https://github.com/openfga/fga-spring-boot/issues/2
- [x] #14
